export const ActionTypes = {
  SET_LOADER: 'SET_LOADER',
  RESET_LOADER: 'RESET_LOADER',

  SIGN_UP_USER: 'SIGN_UP_USER',
  SET_LOGIN: 'SET_LOGIN',
  SET_USER_ROLE: 'SET_USER_ROLE',
  RESET_LOGIN: 'RESET_LOGIN',
  RESET_USER_ROLE: 'RESET_USER_ROLE',
  SET_USERS: 'SET_USERS',
  USER: 'USER',
  UPDATE_USER: 'UPDATE_USER',

  SELECTED_BLOG: 'SELECTED_BLOG',
  ADD_BLOG: 'ADD_BLOG',
  SET_BLOGS: 'SET_BLOGS',
  UPDATE_BLOG: 'UPDATE_BLOG',
  USER_BLOGS: 'USER_BLOGS',
  OTHER_USER_BLOGS: 'OTHER_USER_BLOGS',
  SET_SEARCH_INPUT: 'SET_SEARCH_INPUT',
  SET_SEARCH_BLOGS: 'SET_SEARCH_BLOGS',
  RESET_SEARCH_BLOGS: 'RESET_SEARCH_BLOGS',

  ADD_CATEGORY: 'ADD_CATEGORY',
  SET_CATEGORIES: 'SET_CATEGORIES',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  SELECTED_CATEGORY: 'SELECTED_CATEGORY',
}
